HAI 1.2
  I HAS A KITTEH ITZ 3 

  KITTEH IS NOW A NUMBR

  IM IN YR COMPOOTER UPPIN YR COUNTERZ TIL BOTH SAEM COUNTERZ AN KITTEH

    I HAS A OUTPUT ITZ A YARN
    WIN, O RLY? 
        YA RLY, OUTPUT R ":3"
        NO WAI, OUTPUT R ":["
    OIC

    VISIBLE SMOOSH "CAN HAS PRINT " SUM OF COUNTERZ AN 1 ": " OUTPUT MKAY

  IM OUTTA YR COMPOOTER

KTHXBYE
