HAI 1.2
  I HAS A LAWNZTEHDO ITZ 3 

  LAWNZTEHDO IS NOW A NUMBR

  IM IN YR LAWNMOWAR UPPIN YR LAWNNUMBR TIL BOTH SAEM LAWNNUMBR AN LAWNZTEHDO

    I HAS A REPORTS ITZ A YARN
    FAIL, O RLY? 
        YA RLY, REPORTS R "YES"
        NO WAI, REPORTS R "NO"
    OIC

    VISIBLE SMOOSH "CAN HAS PRINT " SUM OF LAWNNUMBR AN 1 ": " REPORTS MKAY

  IM OUTTA YR LAWNMOWAR

KTHXBYE
